// Generates tenant/dr-sindhu.json (ClinicFlow247 onboarding file, same schema as
// the SMSDC tenant file in D:\ClinicFlow\clinicflow-api\tools\tenant-onboarding) from /content, so a doctor rename or a new
// phone number is edited once in /content and re-exported with: npm run tenant
// PREPARE ONLY: never run the importer against staging/production without the owner's explicit approval.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const read = (f) => JSON.parse(fs.readFileSync(path.join(root, 'content', f), 'utf8'));
const clinic = read('clinic.json');
const brand = read('brand.json');
const plan = read('plan.json').plan;
const { doctors } = read('doctors.json');
const services = read('services.json');
const faqs = read('faqs.json');
const portal = read('portal.json');

const approved = (f) => f.status === 'approved';
const DAY = { monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday' };
const byId = Object.fromEntries(doctors.map((d) => [d.id, d]));
// Same wording as the website's formatter (src/lib/hours.ts → hoursSummary/formatSessions), computed from content.
const t12 = (t) => { const [h, m] = t.split(':').map(Number); return `${h % 12 || 12}:${String(m).padStart(2, '0')} ${h >= 12 ? 'PM' : 'AM'}`; };
const part = (t) => (Number(t.slice(0, 2)) < 12 ? 'Morning' : Number(t.slice(0, 2)) < 17 ? 'Afternoon' : 'Evening');
const sessionsText = (ss) => ss.map((x) => `${part(x.opens)} ${t12(x.opens)} – ${t12(x.closes)}`).join(' & ');
const openDays = clinic.hours.days.filter((d) => d.sessions.length);
const closedDays = clinic.hours.days.filter((d) => !d.sessions.length);
const hoursText = `${DAY[openDays[0].day]}–${DAY[openDays[openDays.length - 1].day]}, ${sessionsText(openDays[0].sessions)}; ${closedDays.map((d) => DAY[d.day]).join(', ')} closed`;
const address = [clinic.address.doorNumber, clinic.address.street, clinic.address.landmark && `near ${clinic.address.landmark}`, clinic.address.locality, `${clinic.address.region}${clinic.address.postalCode ? ` ${clinic.address.postalCode}` : ''}`]
  .filter(Boolean)
  .join(', ');
const alias = (tag) => `appsdevpreneur369+drsdc-${tag}@gmail.com`;

const tenant = {
  _note:
    'Dr. Sindhu Dental Clinic (DRSDC) -- ClinicFlow247 STARTER tenant. GENERATED by `npm run tenant` from D:\\DR-SINDHU\\content (edit content, not this file). PREPARE ONLY: not copied into D:\\ClinicFlow and not run against staging/production. Passwords are deliberately null so the API uses the invite-by-email flow. Login emails are PLACEHOLDER plus-aliases of the account owner\'s own test inbox (same convention as the SMSDC tenant file) -- replace with the doctors\' real emails before go-live.',
  clinic: {
    name: clinic.name.value,
    address,
    _note_address: 'PLACEHOLDER: door number, landmark and PIN still to come (DRSDC_PendingItems.md).',
    city: clinic.address.locality,
    country: clinic.address.countryName,
    phone: approved(clinic.phone) ? clinic.phone.e164 : null,
    email: approved(clinic.email) ? clinic.email.value : null,
    _note_email: 'Clinic email not provided yet -> null (never invent one).',
    plan: plan.toUpperCase(),
    slug: portal.clinicSlug,
    _note_slug: 'Passed explicitly to POST /clinics; must be free on the target environment (check GET /clinics/public/<slug> -> 404 first).',
    whiteLabel: false,
    _note_whiteLabel: 'STARTER: portal/login/booking pages keep standard ClinicFlow247 branding. Branding, theme tokens, logo and subdomain switch on only with ENTERPRISE (docs/UPGRADE_TO_ENTERPRISE.md).',
    appTitle: null,
    logoUrl: null,
    faviconUrl: null,
    themeTokens: null,
    _enterpriseThemeTokens: {
      _note: 'Not applied on STARTER. Move to clinic.themeTokens on upgrade.',
      primaryColor: brand.colors.primary,
      primaryHoverColor: brand.colors.primaryHover,
      primaryPressedColor: brand.colors.primaryDeep,
      secondaryColor: brand.colors.mintStrong,
      accentColor: brand.colors.cta,
      backgroundColor: brand.colors.background,
      surfaceColor: brand.colors.surface,
      textColor: brand.colors.text,
      textSecondaryColor: brand.colors.textSecondary,
      borderColor: brand.colors.border,
      fontHeading: brand.fonts.heading,
      fontBody: brand.fonts.body,
    },
    businessHours: clinic.hours.days.flatMap((d) => d.sessions.map((s) => ({ dayOfWeek: DAY[d.day], opens: s.opens, closes: s.closes }))),
    _note_businessHours: 'Split sessions = two entries per day (same approach as the SMSDC tenant file). Session times approved; Mon–Sat working days are an ASSUMPTION until the clinic confirms. Display only: slots come from each doctor\'s weekly schedule.',
    socialLinks: approved(clinic.whatsapp) ? { whatsapp: `https://wa.me/${clinic.whatsapp.e164.replace(/\D/g, '')}` } : {},
    whatsappNumber: approved(clinic.whatsapp) ? clinic.whatsapp.e164 : null,
    customDomain: null,
    coverPhotoUrl: null,
    description: clinic.description.value,
  },
  owner: {
    email: alias('admin'),
    password: null,
    firstName: 'Sindhu',
    lastName: 'MDS',
    phone: null,
    _note: 'CLINIC_ADMIN (owner) login, separate from Dr. Sindhu\'s DOCTOR account (one AppUser cannot hold two roles). PLACEHOLDER email.',
  },
  _note_doctorNames: 'The API requires a non-blank lastName. Doctors with a single name get lastName "MDS" (PLACEHOLDER), as in the SMSDC tenant file. The website matches ClinicFlow doctors by first name when content lastName is empty.',
  doctors: doctors.map((d) => ({
    email: alias(d.slug.replace(/^dr-/, '')),
    password: null,
    firstName: d.firstName,
    lastName: d.lastName || 'MDS',
    phone: null,
    mciRegistrationNumber: d.registrationNumber || `PENDING-VERIFICATION-${d.firstName.toUpperCase()}`,
    specialization: d.role && d.isHead ? `${d.specialty} · ${d.role}` : d.specialty,
    qualification: d.qualification,
    bio: d.bio.join(' '),
    ...(d.isHead ? { isOwner: true } : {}),
  })),
  _note_doctorsNotInImporter: `The importer does not set appointmentDurationMinutes or weekly schedules. Apply afterwards via the admin API: PUT /clinics/{id}/doctors/{doctorId} {appointmentDurationMinutes: ${read('doctors.json').consultSlotMinutes}}, then POST /clinics/{id}/doctors/{doctorId}/schedules per day (Mon–Sat 10:00–14:00 and 17:00–21:00, PLACEHOLDER). No photos: initials avatars.`,
  heroBanners: [],
  testimonials: [],
  _note_testimonials: 'None by policy: never invent reviews. Review requests are a Pro/Enterprise feature.',
  faqs: faqs.items.slice(0, 6).map((f) => ({ question: f.q, answer: f.a.replace('{{hoursSummary}}', hoursText.replace(/\.$/, '')) })),
  processSteps: [],
  videos: [],
  treatments: ['pro', 'enterprise'].includes(plan) ? treatmentRows() : [],
  _note_treatmentsPlan:
    'Core gates treatments + gallery to PRO and above (PlanService "gallery"; confirmed on a local API 30 Sep 2026: 402 GALLERY_NOT_ENTITLED on STARTER). The website shows all 9 treatments from its own content either way. On upgrade, re-run `npm run tenant` with plan.json = enterprise to fill this list.',
  _upgradeTreatments: ['pro', 'enterprise'].includes(plan) ? [] : treatmentRows(),
  _note_treatments: '9 categories from content/services.json; sub-treatments folded into the description (no sub-treatment entity in core). No prices.',
  contentPages: [],
  flags: [
    'DRSDC: plan STARTER, whiteLabel false -- do not upload logo/theme (Enterprise-only).',
    'DRSDC: treatments are not imported on STARTER (core: Pro+ only); the website lists them from its own content.',
    'DRSDC: all doctors use placeholder mciRegistrationNumber PENDING-VERIFICATION-<NAME>; replace with State Dental Council numbers before any real e-prescription.',
    'DRSDC: Dr. Sindhu and Dr. Preethi have placeholder lastName "MDS" (API requires a surname).',
    'DRSDC: clinic email and address PIN/landmark are placeholders.',
    'DRSDC: implants (prosthetic), dentures and orthodontics have no in-house specialist yet -- routed to Dr. Sindhu for consultation.',
    'DRSDC: these three consultants also appear in the SMSDC tenant; ClinicFlow accounts must still be unique per email.',
    'DRSDC: new clinics start PENDING -- a super-admin must set status ACTIVE (PUT /clinics/{id}) before the public booking page works; the importer does not do this.',
  ],
};

function treatmentRows() {
  return services.categories.map((c, i) => {
    const docs = [...new Set([...c.doctors, ...c.subTreatments.flatMap((s) => s.doctors ?? [])])].map((id) => byId[id].displayName);
    return {
      title: c.title,
      category: c.shortTitle,
      description: `${c.subTreatments.map((s) => s.title).join(' · ')}. With ${docs.join(' and ')}.${c.confirmSpecialist ? ' First consultation with Dr. Sindhu (specialist to be confirmed).' : ''} ${services.priceNote}`,
      displayOrder: i,
    };
  });
}


const out = path.join(root, 'tenant', 'dr-sindhu.json');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `${JSON.stringify(tenant, null, 2)}\n`);
console.log(`wrote ${path.relative(root, out)} (${tenant.doctors.length} doctors, ${tenant.treatments.length} treatments, ${tenant.clinic.businessHours.length} hour entries)`);
